// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_7.Data;

namespace Project_7.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20240824135134_SeedProductData")]
    partial class SeedProductData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project_7.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 8, 24, 16, 51, 34, 409, DateTimeKind.Local).AddTicks(9208),
                            Name = "Computer",
                            Price = 3500m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 8, 24, 16, 51, 34, 410, DateTimeKind.Local).AddTicks(6525),
                            Name = "Phone",
                            Price = 500m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 8, 24, 16, 51, 34, 410, DateTimeKind.Local).AddTicks(6537),
                            Name = "Mouse",
                            Price = 150m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 8, 24, 16, 51, 34, 410, DateTimeKind.Local).AddTicks(6539),
                            Name = "Keyboard",
                            Price = 350m,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
